#!/usr/bin/env python2
#-*-coding:utf-8-*-

# the book info class

import json

class book:
    def __init__(self):
        self.id="id"
        self.isbn10="isbn10"
        self.isbn13="isbn13"
        self.title="title"
        self.origin_title="origin_title"
        self.alt_title="alt_title"
        self.subtitle="subtitle"
        self.url="http://api.douban.com"
        self.alt="http://api.douban.com"
        self.image=""
        self.images=[]
        self.author=[];
        self.translator=[];
        self.publisher="publisher"
        self.pubdate="pubdate"
        self.rating=""
        self.tags=""
        self.binding=""
        self.price="1.00"
        self.pages="100"
        self.author_intor=""
        self.summary=""
    def loadjson(self,jsondata):
        self.id=jsondata['id']
        self.isbn10=jsondata['isbn10']
        self.isbn13=jsondata['isbn13']
        self.title=jsondata['title']
        self.origin_title=jsondata['origin_title']
        self.subtitle=jsondata['subtitle']
        self.url=jsondata['url']
        self.alt=jsondata['alt']
        self.image=jsondata['image']
        self.images=jsondata['images']
        self.author=jsondata['author']
        self.translator=jsondata['translator']
        self.publisher=jsondata['publisher']
        self.pubdate=jsondata['pubdate']
        self.rating=jsondata['rating']
        self.tags=jsondata['tags']
        self.binding=jsondata['binding']
        self.price=jsondata['price']
        self.pages=jsondata['pages']
        self.author_intor=jsondata['author_intor']
        self.summary=jsondata['summary']

    def showinfo(self):
        print self.id
        print self.isbn10
        print self.isbn13
        print self.title
        print self.origin_title
        print self.alt_title
        print self.subtitle
        print self.url
        print self.alt
        print self.image
        print self.images
        print self.author
        print self.translator
        print self.publisher
        print self.pubdate
        print self.rating
        print self.tags
        print self.binding
        print self.price
        print self.pages
        print self.author_intor
        print self.summary

        

        

if __name__=='__main__':
    mbook=book()
    f=open("data.txt","r")
    data=f.read()
    booksjson=json.loads(data)
    mbook.loadjson(booksjson['books'][0])

    mbook.showinfo()







